### ISSUE TITLE
Make the serializer configurable

### ISSUE THREAD

**Issue by benniekrijger** [tradecloud/akka-kafka#4]
Problem:
Currently the default akka remote serializer is used, see: nl.tradecloud.kafka.KafkaMessageSerializer

This serializer wraps the serialized messages in a wrapper message: akka.remote.WireFormats.SerializedMessage

The problem is, that when for example interacting with systems outside akka, this wrapper message is not accessible and thereby usable.

Solution:
Extract serialization (make it modular), use a self defined messageProtocol like SerializedMessage

**Comment by benniekrijger** [comment]
@vovinacci @marcmatt @ralph-tradecloud-nl agreed?

**Comment by vovinacci** [comment]
Closing this issue as outdated
